# Generated by Django 2.1.4 on 2019-02-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='number_r',
            new_name='count',
        ),
    ]
