# Generated by Django 2.1.4 on 2019-02-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0003_auto_20190214_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='number_int',
            field=models.IntegerField(default=0),
        ),
    ]
